/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Caller : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Caller(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Caller obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Caller() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          examplePINVOKE.delete_Caller(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Caller() : this(examplePINVOKE.new_Caller(), true) {
  }

  public void delCallback() {
    examplePINVOKE.Caller_delCallback(swigCPtr);
  }

  public void setCallback(Callback cb) {
    examplePINVOKE.Caller_setCallback(swigCPtr, Callback.getCPtr(cb));
  }

  public void resetCallback() {
    examplePINVOKE.Caller_resetCallback(swigCPtr);
  }

  public void call() {
    examplePINVOKE.Caller_call(swigCPtr);
  }

}
