/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class example {
  public static int do_op(int a, int b, SWIGTYPE_p_f_int_int__int op) {
    int ret = examplePINVOKE.do_op(a, b, SWIGTYPE_p_f_int_int__int.getCPtr(op));
    return ret;
  }

  public static SWIGTYPE_p_f_int_int__int funcvar {
    set {
      examplePINVOKE.funcvar_set(SWIGTYPE_p_f_int_int__int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = examplePINVOKE.funcvar_get();
      SWIGTYPE_p_f_int_int__int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_int_int__int(cPtr, false);
      return ret;
    } 
  }

  public static readonly SWIGTYPE_p_f_int_int__int ADD = new SWIGTYPE_p_f_int_int__int(examplePINVOKE.ADD_get(), false);
  public static readonly SWIGTYPE_p_f_int_int__int SUB = new SWIGTYPE_p_f_int_int__int(examplePINVOKE.SUB_get(), false);
  public static readonly SWIGTYPE_p_f_int_int__int MUL = new SWIGTYPE_p_f_int_int__int(examplePINVOKE.MUL_get(), false);
}
