/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum GL_DIALOG_CONTROL_TYPES {
  GL_TEXT_CONTROL = 1,
  GL_TOGGLE_CONTROL,
  GL_SLIDER_CONTROL,
  GL_CONTROL_MAX_TYPE
}
