/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class GL_Simplex1to4 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GL_Simplex1to4(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GL_Simplex1to4 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GL_Simplex1to4() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenGLSupportPINVOKE.delete_GL_Simplex1to4(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public GL_Simplex1to4() : this(OpenGLSupportPINVOKE.new_GL_Simplex1to4(), true) {
  }

  public void calcClosest(SWIGTYPE_p_float m) {
    OpenGLSupportPINVOKE.GL_Simplex1to4_calcClosest(swigCPtr, SWIGTYPE_p_float.getCPtr(m));
  }

  public void setSimplexSolver(SWIGTYPE_p_btSimplexSolverInterface simplexSolver) {
    OpenGLSupportPINVOKE.GL_Simplex1to4_setSimplexSolver(swigCPtr, SWIGTYPE_p_btSimplexSolverInterface.getCPtr(simplexSolver));
  }

}
