/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class GL_ToggleControl : GL_DialogControl {
  private HandleRef swigCPtr;

  internal GL_ToggleControl(IntPtr cPtr, bool cMemoryOwn) : base(OpenGLSupportPINVOKE.GL_ToggleControl_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GL_ToggleControl obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GL_ToggleControl() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenGLSupportPINVOKE.delete_GL_ToggleControl(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public SWIGTYPE_p_btCollisionObject m_toggleBody {
    set {
      OpenGLSupportPINVOKE.GL_ToggleControl_m_toggleBody_set(swigCPtr, SWIGTYPE_p_btCollisionObject.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OpenGLSupportPINVOKE.GL_ToggleControl_m_toggleBody_get(swigCPtr);
      SWIGTYPE_p_btCollisionObject ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionObject(cPtr, false);
      return ret;
    } 
  }

  public GL_DialogWindow m_parentWindow {
    set {
      OpenGLSupportPINVOKE.GL_ToggleControl_m_parentWindow_set(swigCPtr, GL_DialogWindow.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OpenGLSupportPINVOKE.GL_ToggleControl_m_parentWindow_get(swigCPtr);
      GL_DialogWindow ret = (cPtr == IntPtr.Zero) ? null : new GL_DialogWindow(cPtr, false);
      return ret;
    } 
  }

  public string m_toggleText {
    set {
      OpenGLSupportPINVOKE.GL_ToggleControl_m_toggleText_set(swigCPtr, value);
    } 
    get {
      string ret = OpenGLSupportPINVOKE.GL_ToggleControl_m_toggleText_get(swigCPtr);
      return ret;
    } 
  }

  public bool m_active {
    set {
      OpenGLSupportPINVOKE.GL_ToggleControl_m_active_set(swigCPtr, value);
    } 
    get {
      bool ret = OpenGLSupportPINVOKE.GL_ToggleControl_m_active_get(swigCPtr);
      return ret;
    } 
  }

  public GL_ToggleControl(string toggleText, SWIGTYPE_p_btCollisionObject toggleBody, GL_DialogWindow parentWindow) : this(OpenGLSupportPINVOKE.new_GL_ToggleControl(toggleText, SWIGTYPE_p_btCollisionObject.getCPtr(toggleBody), GL_DialogWindow.getCPtr(parentWindow)), true) {
  }

  public override void draw(SWIGTYPE_p_int parentHorPos, SWIGTYPE_p_int parentVertPos, float deltaTime) {
    OpenGLSupportPINVOKE.GL_ToggleControl_draw(swigCPtr, SWIGTYPE_p_int.getCPtr(parentHorPos), SWIGTYPE_p_int.getCPtr(parentVertPos), deltaTime);
    if (OpenGLSupportPINVOKE.SWIGPendingException.Pending) throw OpenGLSupportPINVOKE.SWIGPendingException.Retrieve();
  }

}
