/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class stbi_io_callbacks : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal stbi_io_callbacks(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(stbi_io_callbacks obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~stbi_io_callbacks() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenGLSupportPINVOKE.delete_stbi_io_callbacks(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_void_p_char_int__int read {
    set {
      OpenGLSupportPINVOKE.stbi_io_callbacks_read_set(swigCPtr, SWIGTYPE_p_f_p_void_p_char_int__int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OpenGLSupportPINVOKE.stbi_io_callbacks_read_get(swigCPtr);
      SWIGTYPE_p_f_p_void_p_char_int__int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_void_p_char_int__int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_void_unsigned_int__void skip {
    set {
      OpenGLSupportPINVOKE.stbi_io_callbacks_skip_set(swigCPtr, SWIGTYPE_p_f_p_void_unsigned_int__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OpenGLSupportPINVOKE.stbi_io_callbacks_skip_get(swigCPtr);
      SWIGTYPE_p_f_p_void_unsigned_int__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_void_unsigned_int__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_void__int eof {
    set {
      OpenGLSupportPINVOKE.stbi_io_callbacks_eof_set(swigCPtr, SWIGTYPE_p_f_p_void__int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OpenGLSupportPINVOKE.stbi_io_callbacks_eof_get(swigCPtr);
      SWIGTYPE_p_f_p_void__int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_void__int(cPtr, false);
      return ret;
    } 
  }

  public stbi_io_callbacks() : this(OpenGLSupportPINVOKE.new_stbi_io_callbacks(), true) {
  }

}
