/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Employee : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Employee(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Employee obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Employee() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          examplePINVOKE.delete_Employee(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Employee(string n) : this(examplePINVOKE.new_Employee(n), true) {
    SwigDirectorConnect();
  }

  public virtual string getTitle() {
    string ret = (SwigDerivedClassHasMethod("getTitle", swigMethodTypes0) ? examplePINVOKE.Employee_getTitleSwigExplicitEmployee(swigCPtr) : examplePINVOKE.Employee_getTitle(swigCPtr));
    return ret;
  }

  public virtual string getName() {
    string ret = (SwigDerivedClassHasMethod("getName", swigMethodTypes1) ? examplePINVOKE.Employee_getNameSwigExplicitEmployee(swigCPtr) : examplePINVOKE.Employee_getName(swigCPtr));
    return ret;
  }

  public virtual string getPosition() {
    string ret = (SwigDerivedClassHasMethod("getPosition", swigMethodTypes2) ? examplePINVOKE.Employee_getPositionSwigExplicitEmployee(swigCPtr) : examplePINVOKE.Employee_getPosition(swigCPtr));
    return ret;
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("getTitle", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateEmployee_0(SwigDirectorgetTitle);
    if (SwigDerivedClassHasMethod("getName", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateEmployee_1(SwigDirectorgetName);
    if (SwigDerivedClassHasMethod("getPosition", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateEmployee_2(SwigDirectorgetPosition);
    examplePINVOKE.Employee_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(Employee));
    return hasDerivedMethod;
  }

  private string SwigDirectorgetTitle() {
    return getTitle();
  }

  private string SwigDirectorgetName() {
    return getName();
  }

  private string SwigDirectorgetPosition() {
    return getPosition();
  }

  public delegate string SwigDelegateEmployee_0();
  public delegate string SwigDelegateEmployee_1();
  public delegate string SwigDelegateEmployee_2();

  private SwigDelegateEmployee_0 swigDelegate0;
  private SwigDelegateEmployee_1 swigDelegate1;
  private SwigDelegateEmployee_2 swigDelegate2;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] {  };
  private static Type[] swigMethodTypes2 = new Type[] {  };
}
