/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_example_WRAP_H_
#define SWIG_example_WRAP_H_

class SwigDirector_Employee : public Employee, public Swig::Director {

public:
    SwigDirector_Employee(char const *n);
    virtual std::string getTitle();
    virtual std::string getName();
    virtual std::string getPosition() const;
    virtual ~SwigDirector_Employee();

    typedef char * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef char * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef char * (SWIGSTDCALL* SWIG_Callback2_t)();
    void swig_connect_director(SWIG_Callback0_t callbackgetTitle, SWIG_Callback1_t callbackgetName, SWIG_Callback2_t callbackgetPosition);

private:
    SWIG_Callback0_t swig_callbackgetTitle;
    SWIG_Callback1_t swig_callbackgetName;
    SWIG_Callback2_t swig_callbackgetPosition;
    void swig_init_callbacks();
};

class SwigDirector_Manager : public Manager, public Swig::Director {

public:
    SwigDirector_Manager(char const *n);
    virtual std::string getTitle();
    virtual std::string getName();
    virtual std::string getPosition() const;
    virtual ~SwigDirector_Manager();

    typedef char * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef char * (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef char * (SWIGSTDCALL* SWIG_Callback2_t)();
    void swig_connect_director(SWIG_Callback0_t callbackgetTitle, SWIG_Callback1_t callbackgetName, SWIG_Callback2_t callbackgetPosition);

private:
    SWIG_Callback0_t swig_callbackgetTitle;
    SWIG_Callback1_t swig_callbackgetName;
    SWIG_Callback2_t swig_callbackgetPosition;
    void swig_init_callbacks();
};


#endif
