/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class examplePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("example", EntryPoint="SWIGRegisterExceptionCallbacks_example")]
    public static extern void SWIGRegisterExceptionCallbacks_example(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("example", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_example")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_example(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_example(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_example(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(examplePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(examplePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("example", EntryPoint="SWIGRegisterStringCallback_example")]
    public static extern void SWIGRegisterStringCallback_example(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_example(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static examplePINVOKE() {
  }


  [DllImport("example", EntryPoint="CSharp_new_Employee")]
  public static extern IntPtr new_Employee(string jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_getTitle")]
  public static extern string Employee_getTitle(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_getTitleSwigExplicitEmployee")]
  public static extern string Employee_getTitleSwigExplicitEmployee(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_getName")]
  public static extern string Employee_getName(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_getNameSwigExplicitEmployee")]
  public static extern string Employee_getNameSwigExplicitEmployee(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_getPosition")]
  public static extern string Employee_getPosition(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_getPositionSwigExplicitEmployee")]
  public static extern string Employee_getPositionSwigExplicitEmployee(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_delete_Employee")]
  public static extern void delete_Employee(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Employee_director_connect")]
  public static extern void Employee_director_connect(HandleRef jarg1, Employee.SwigDelegateEmployee_0 delegate0, Employee.SwigDelegateEmployee_1 delegate1, Employee.SwigDelegateEmployee_2 delegate2);

  [DllImport("example", EntryPoint="CSharp_new_Manager")]
  public static extern IntPtr new_Manager(string jarg1);

  [DllImport("example", EntryPoint="CSharp_Manager_getPosition")]
  public static extern string Manager_getPosition(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Manager_getPositionSwigExplicitManager")]
  public static extern string Manager_getPositionSwigExplicitManager(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_delete_Manager")]
  public static extern void delete_Manager(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Manager_director_connect")]
  public static extern void Manager_director_connect(HandleRef jarg1, Manager.SwigDelegateManager_0 delegate0, Manager.SwigDelegateManager_1 delegate1, Manager.SwigDelegateManager_2 delegate2);

  [DllImport("example", EntryPoint="CSharp_new_EmployeeList")]
  public static extern IntPtr new_EmployeeList();

  [DllImport("example", EntryPoint="CSharp_EmployeeList_addEmployee")]
  public static extern void EmployeeList_addEmployee(HandleRef jarg1, HandleRef jarg2);

  [DllImport("example", EntryPoint="CSharp_EmployeeList_get_item")]
  public static extern IntPtr EmployeeList_get_item(HandleRef jarg1, int jarg2);

  [DllImport("example", EntryPoint="CSharp_delete_EmployeeList")]
  public static extern void delete_EmployeeList(HandleRef jarg1);

  [DllImport("example", EntryPoint="CSharp_Manager_SWIGUpcast")]
  public static extern IntPtr Manager_SWIGUpcast(IntPtr jarg1);
}
