/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class example {
  public static int maxint(int a, int b) {
    int ret = examplePINVOKE.maxint(a, b);
    return ret;
  }

  public static double maxdouble(double a, double b) {
    double ret = examplePINVOKE.maxdouble(a, b);
    return ret;
  }

}
