/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_LinearMath_WRAP_H_
#define SWIG_LinearMath_WRAP_H_

class SwigDirector_btIDebugDraw : public btIDebugDraw, public Swig::Director {

public:
    SwigDirector_btIDebugDraw();
    virtual ~SwigDirector_btIDebugDraw();
    virtual void drawLine(btVector3 const &from, btVector3 const &to, btVector3 const &color);
    virtual void drawLine(btVector3 const &from, btVector3 const &to, btVector3 const &fromColor, btVector3 const &toColor);
    virtual void drawSphere(btScalar radius, btTransform const &transform, btVector3 const &color);
    virtual void drawSphere(btVector3 const &p, btScalar radius, btVector3 const &color);
    virtual void drawTriangle(btVector3 const &v0, btVector3 const &v1, btVector3 const &v2, btVector3 const &arg3, btVector3 const &arg4, btVector3 const &arg5, btVector3 const &color, btScalar alpha);
    virtual void drawTriangle(btVector3 const &v0, btVector3 const &v1, btVector3 const &v2, btVector3 const &color, btScalar arg4);
    virtual void drawContactPoint(btVector3 const &PointOnB, btVector3 const &normalOnB, btScalar distance, int lifeTime, btVector3 const &color);
    virtual void reportErrorWarning(char const *warningString);
    virtual void draw3dText(btVector3 const &location, char const *textString);
    virtual void setDebugMode(int debugMode);
    virtual int getDebugMode() const;
    virtual void drawAabb(btVector3 const &from, btVector3 const &to, btVector3 const &color);
    virtual void drawTransform(btTransform const &transform, btScalar orthoLen);
    virtual void drawArc(btVector3 const &center, btVector3 const &normal, btVector3 const &axis, btScalar radiusA, btScalar radiusB, btScalar minAngle, btScalar maxAngle, btVector3 const &color, bool drawSect, btScalar stepDegrees = btScalar(10.f));
    virtual void drawSpherePatch(btVector3 const &center, btVector3 const &up, btVector3 const &axis, btScalar radius, btScalar minTh, btScalar maxTh, btScalar minPs, btScalar maxPs, btVector3 const &color, btScalar stepDegrees = btScalar(10.f));
    virtual void drawBox(btVector3 const &bbMin, btVector3 const &bbMax, btVector3 const &color);
    virtual void drawBox(btVector3 const &bbMin, btVector3 const &bbMax, btTransform const &trans, btVector3 const &color);
    virtual void drawCapsule(btScalar radius, btScalar halfHeight, int upAxis, btTransform const &transform, btVector3 const &color);
    virtual void drawCylinder(btScalar radius, btScalar halfHeight, int upAxis, btTransform const &transform, btVector3 const &color);
    virtual void drawCone(btScalar radius, btScalar height, int upAxis, btTransform const &transform, btVector3 const &color);
    virtual void drawPlane(btVector3 const &planeNormal, btScalar planeConst, btTransform const &transform, btVector3 const &color);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *, void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(float, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, float, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, void *, void *, void *, void *, void *, void *, float);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *, void *, void *, float);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, float, int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(char *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(int);
    typedef int (SWIGSTDCALL* SWIG_Callback10_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, float);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, void *, float, float, float, float, void *, unsigned int, float);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, void *, float, float, float, float, void *, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, void *, void *, float, float, float, float, float, void *, float);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(void *, void *, void *, float, float, float, float, float, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)(void *, void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(float, float, int, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(float, float, int, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(float, float, int, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(void *, float, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackdrawLine__SWIG_0, SWIG_Callback1_t callbackdrawLine__SWIG_1, SWIG_Callback2_t callbackdrawSphere__SWIG_0, SWIG_Callback3_t callbackdrawSphere__SWIG_1, SWIG_Callback4_t callbackdrawTriangle__SWIG_0, SWIG_Callback5_t callbackdrawTriangle__SWIG_1, SWIG_Callback6_t callbackdrawContactPoint, SWIG_Callback7_t callbackreportErrorWarning, SWIG_Callback8_t callbackdraw3dText, SWIG_Callback9_t callbacksetDebugMode, SWIG_Callback10_t callbackgetDebugMode, SWIG_Callback11_t callbackdrawAabb, SWIG_Callback12_t callbackdrawTransform, SWIG_Callback13_t callbackdrawArc__SWIG_0, SWIG_Callback14_t callbackdrawArc__SWIG_1, SWIG_Callback15_t callbackdrawSpherePatch__SWIG_0, SWIG_Callback16_t callbackdrawSpherePatch__SWIG_1, SWIG_Callback17_t callbackdrawBox__SWIG_0, SWIG_Callback18_t callbackdrawBox__SWIG_1, SWIG_Callback19_t callbackdrawCapsule, SWIG_Callback20_t callbackdrawCylinder, SWIG_Callback21_t callbackdrawCone, SWIG_Callback22_t callbackdrawPlane);

private:
    SWIG_Callback0_t swig_callbackdrawLine__SWIG_0;
    SWIG_Callback1_t swig_callbackdrawLine__SWIG_1;
    SWIG_Callback2_t swig_callbackdrawSphere__SWIG_0;
    SWIG_Callback3_t swig_callbackdrawSphere__SWIG_1;
    SWIG_Callback4_t swig_callbackdrawTriangle__SWIG_0;
    SWIG_Callback5_t swig_callbackdrawTriangle__SWIG_1;
    SWIG_Callback6_t swig_callbackdrawContactPoint;
    SWIG_Callback7_t swig_callbackreportErrorWarning;
    SWIG_Callback8_t swig_callbackdraw3dText;
    SWIG_Callback9_t swig_callbacksetDebugMode;
    SWIG_Callback10_t swig_callbackgetDebugMode;
    SWIG_Callback11_t swig_callbackdrawAabb;
    SWIG_Callback12_t swig_callbackdrawTransform;
    SWIG_Callback13_t swig_callbackdrawArc__SWIG_0;
    SWIG_Callback14_t swig_callbackdrawArc__SWIG_1;
    SWIG_Callback15_t swig_callbackdrawSpherePatch__SWIG_0;
    SWIG_Callback16_t swig_callbackdrawSpherePatch__SWIG_1;
    SWIG_Callback17_t swig_callbackdrawBox__SWIG_0;
    SWIG_Callback18_t swig_callbackdrawBox__SWIG_1;
    SWIG_Callback19_t swig_callbackdrawCapsule;
    SWIG_Callback20_t swig_callbackdrawCylinder;
    SWIG_Callback21_t swig_callbackdrawCone;
    SWIG_Callback22_t swig_callbackdrawPlane;
    void swig_init_callbacks();
};


#endif
